In [256]:
%matplotlib inline

In [257]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier

In [258]:
folder_path = "c:/users/jeff/dropbox/kaggle_animal_shelter/"

In [259]:
train = pd.read_csv(folder_path + "train.csv", encoding='utf-8')
test = pd.read_csv(folder_path + "test.csv", encoding='utf-8')

In [273]:
combined = train.append(test)

In [274]:
combined

,AgeuponOutcome,AnimalID,AnimalType,Breed,Color,DateTime,ID,Name,OutcomeSubtype,OutcomeType,SexuponOutcome
0,1 year,A671945,Dog,Shetland Sheepdog Mix,Brown/White,2014-02-12 18:22:00,NaN,Hambone,NaN,Return_to_owner,Neutered Male
1,1 year,A656520,Cat,Domestic Shorthair Mix,Cream Tabby,2013-10-13 12:44:00,NaN,Emily,Suffering,Euthanasia,Spayed Female
2,2 years,A686464,Dog,Pit Bull Mix,Blue/White,2015-01-31 12:28:00,NaN,Pearce,Foster,Adoption,Neutered Male
3,3 weeks,A683430,Cat,Domestic Shorthair Mix,Blue Cream,2014-07-11 19:09:00,NaN,NaN,Partner,Transfer,Intact Male
4,2 years,A667013,Dog,Lhasa Apso/Miniature Poodle,Tan,2013-11-15 12:52:00,NaN,NaN,Partner,Transfer,Neutered Male
5,1 month,A677334,Dog,Cairn Terrier/Chihuahua Shorthair,Black/Tan,2014-04-25 13:04:00,NaN,Elsa,Partner,Transfer,Intact Female
6,3 weeks,A699218,Cat,Domestic Shorthair Mix,Blue Tabby,2015-03-28 13:11:00,NaN,Jimmy,Partner,Transfer,Intact Male
7,3 weeks,A701489,Cat,Domestic Shorthair Mix,Brown Tabby,2015-04-30 17:02:00,NaN,NaN,Partner,Transfer,Unknown
8,5 months,A671784,Dog,American Pit Bull Terrier Mix,Red/White,2014-02-04 17:17:00,NaN,Lucy,NaN,Adoption,Spayed Female
9,1 year,A677747,Dog,Cairn Terrier,White,2014-05-03 07:48:00,NaN,NaN,Offsite,Adoption,Spayed Female
10,2 years,A668402,Cat,Domestic Shorthair Mix,Black,2013-12-05 15:50:00,NaN,NaN,SCRP,Transfer,Unknown
11,2 years,A666320,Dog,Miniature Schnauzer Mix,Silver,2013-11-04 14:48:00,NaN,NaN,NaN,Adoption,Spayed Female
12,4 years,A684601,Dog,Pit Bull Mix,Brown,2016-02-03 11:27:00,NaN,Rocket,Foster,Adoption,Neutered Male
13,2 years,A704702,Dog,Yorkshire Terrier Mix,Black/Red,2015-06-08 16:30:00,NaN,Scooter,NaN,Return_to_owner,Neutered Male
14,1 year,A688584,Dog,Great Pyrenees Mix,White/Cream,2015-11-25 15:00:00,NaN,Preston,NaN,Return_to_owner,Neutered Male
15,3 months,A678825,Cat,Domestic Shorthair Mix,Orange Tabby/White,2014-07-12 12:10:00,NaN,Oliver,Foster,Adoption,Neutered Male
16,3 weeks,A678050,Cat,Domestic Shorthair Mix,Brown Tabby,2014-05-03 16:15:00,NaN,NaN,Partner,Transfer,Intact Male
17,2 weeks,A680028,Dog,Pit Bull Mix,Brown/White,2014-06-07 12:54:00,NaN,NaN,Partner,Transfer,Intact Female
18,2 years,A679010,Cat,Angora Mix,White,2014-05-17 11:32:00,NaN,Chrissy,Partner,Transfer,Intact Female
19,1 year,A684787,Dog,Flat Coat Retriever Mix,Black,2014-07-30 17:34:00,NaN,Kuma,NaN,Return_to_owner,Neutered Male
20,2 months,A670658,Dog,Queensland Heeler Mix,Black/White,2014-01-19 15:03:00,NaN,Anders,Partner,Transfer,Intact Male
21,1 year,A708812,Cat,Domestic Shorthair Mix,White,2015-09-18 15:19:00,NaN,Munchkin,Partner,Transfer,Spayed Female
22,2 years,A705262,Dog,Plott Hound/Boxer,Brown Brindle/White,2015-08-15 14:22:00,NaN,Jamaica,NaN,Adoption,Spayed Female
23,10 months,A665781,Dog,German Shepherd Mix,Brown/White,2013-10-28 16:32:00,NaN,Quattro,NaN,Adoption,Neutered Male
24,2 months,A676333,Dog,German Shepherd Mix,Black/Brown,2014-04-09 17:44:00,NaN,Trigger,NaN,Return_to_owner,Neutered Male
25,1 month,A712750,Cat,Domestic Shorthair Mix,Orange Tabby,2015-10-03 15:44:00,NaN,Olive,Partner,Transfer,Intact Female
26,6 months,A718832,Dog,American Staffordshire Terrier Mix,Chocolate/White,2016-01-15 17:31:00,NaN,Nia,NaN,Adoption,Spayed Female
27,5 years,A698777,Dog,Chihuahua Shorthair Mix,White/Tan,2015-03-25 18:50:00,NaN,Chloe,NaN,Adoption,Spayed Female
28,2 months,A715348,Cat,Domestic Shorthair Mix,Cream Tabby/White,2015-11-21 13:01:00,NaN,Cymbale,NaN,Adoption,Spayed Female
29,7 years,A708666,Cat,Russian Blue Mix,Blue,2015-07-30 14:30:00,NaN,Jax,NaN,Return_to_owner,Neutered Male
...,...,...,...,...,...,...,...,...,...,...,...
11426,5 years,NaN,Dog,Boxer Mix,Brown/White,2013-12-28 14:22:00,11427,Fatboy,NaN,NaN,Neutered Male
11427,2 months,NaN,Dog,American Pit Bull Terrier Mix,Brown Brindle,2013-12-21 15:55:00,11428,Calypso,NaN,NaN,Intact Female
11428,3 years,NaN,Dog,Siberian Husky,Red/White,2013-11-15 12:32:00,11429,Bolt,NaN,NaN,Neutered Male
11429,2 years,NaN,Dog,German Shepherd Mix,Sable,2014-02-17 18:04:00,11430,Mary,NaN,NaN,Spayed Female
11430,2 months,NaN,Cat,Domestic Shorthair Mix,Blue,2014-12-08 12:40:00,11431,NaN,NaN,NaN,Spayed Female
11431,2 years,NaN,Cat,Domestic Shorthair Mix,Blue Tabby/White,2015-06-30 09:00:00,11432,NaN,NaN,NaN,Intact Male
11432,5 years,NaN,Dog,Maltese,White,2014-03-21 17:33:00,11433,Fiona,NaN,NaN,Spayed Female
11433,2 months,NaN,Cat,Domestic Shorthair Mix,Black/White,2015-08-16 16:40:00,11434,Evanna,NaN,NaN,Intact Female
11434,6 years,NaN,Dog,Cardigan Welsh Corgi/German Shepherd,Black/Tan,2015-09-06 12:41:00,11435,April,NaN,NaN,Spayed Female
11435,3 weeks,NaN,Cat,Domestic Shorthair Mix,Brown Tabby,2015-08-13 17:09:00,11436,NaN,NaN,NaN,Intact Male
11436,5 months,NaN,Cat,Domestic Shorthair Mix,Black/White,2014-03-21 17:42:00,11437,NaN,NaN,NaN,Neutered Male
11437,6 months,NaN,Dog,Chihuahua Longhair/Dachshund,White/Tan,2014-01-10 13:46:00,11438,Peludita,NaN,NaN,Intact Female
11438,1 month,NaN,Dog,Labrador Retriever Mix,Sable,2015-05-02 20:40:00,11439,NaN,NaN,NaN,Neutered Male
11439,2 years,NaN,Dog,Pit Bull Mix,White/Brown,2014-05-18 16:47:00,11440,Socks,NaN,NaN,Spayed Female
11440,1 week,NaN,Cat,Domestic Shorthair Mix,Brown Tabby,2015-10-20 17:13:00,11441,NaN,NaN,NaN,Unknown
11441,4 years,NaN,Dog,Pit Bull Mix,Blue/White,2015-01-07 17:41:00,11442,Doogie,NaN,NaN,Neutered Male
11442,2 years,NaN,Dog,Chihuahua Shorthair Mix,Tan/White,2015-11-28 16:23:00,11443,Sterling,NaN,NaN,Neutered Male
11443,6 months,NaN,Cat,Domestic Longhair Mix,Torbie,2014-10-04 12:17:00,11444,Bella,NaN,NaN,Spayed Female
11444,2 years,NaN,Cat,Domestic Shorthair Mix,Calico,2014-06-01 17:15:00,11445,NaN,NaN,NaN,Intact Female
11445,2 weeks,NaN,Cat,Domestic Shorthair Mix,White,2015-04-14 14:34:00,11446,NaN,NaN,NaN,Intact Male
11446,2 months,NaN,Cat,Domestic Shorthair Mix,Black,2015-07-19 20:03:00,11447,NaN,NaN,NaN,Neutered Male
11447,1 year,NaN,Dog,Chihuahua Longhair Mix,Orange/Tan,2014-10-19 12:21:00,11448,Sadie,NaN,NaN,Spayed Female
11448,2 months,NaN,Dog,Labrador Retriever Mix,Brown,2014-08-17 17:48:00,11449,NaN,NaN,NaN,Spayed Female
11449,6 months,NaN,Dog,Bearded Collie Mix,Blue Merle/White,2015-07-20 14:55:00,11450,Caicos,NaN,NaN,Spayed Female
11450,10 months,NaN,Dog,Staffordshire Mix,Tan/White,2015-11-05 17:19:00,11451,Cosmo,NaN,NaN,Neutered Male
11451,2 months,NaN,Cat,Domestic Shorthair Mix,Black,2014-07-08 14:50:00,11452,NaN,NaN,NaN,Neutered Male
11452,2 weeks,NaN,Cat,Domestic Shorthair Mix,Blue,2014-10-21 12:57:00,11453,NaN,NaN,NaN,Intact Female
11453,1 year,NaN,Cat,Domestic Shorthair Mix,Calico,2014-09-29 09:00:00,11454,NaN,NaN,NaN,Intact Female
11454,6 years,NaN,Dog,German Shepherd Mix,Black/Tan,2015-09-05 17:16:00,11455,Rambo,NaN,NaN,Neutered Male
11455,4 years,NaN,Dog,Labrador Retriever,Cream,2014-07-12 18:40:00,11456,Gusto,NaN,NaN,Intact Male

### Separating out sex and spay/neuter info

In [264]:
def cleanFeatures(df):
    df['Male'] = (df['SexuponOutcome'] == u'Intact Male') | (df['SexuponOutcome'] == u'Neutered Male')
    df['NeuteredSpayed'] = (df['SexuponOutcome'] == u'Spayed Female') | (df['SexuponOutcome'] == u'Neutered Male')
    df['SexuponOutcomeKnown'] = ~df['SexuponOutcome'].isnull()

    df = df.drop('SexuponOutcome',1)

    df['Dog'] = df['AnimalType'] == u'Dog'
    df = df.drop('AnimalType',1)

    (df['Age (Weeks)'],df['Units']) = (df['AgeuponOutcome'].str.split(' ', expand=True)[0],
                               df['AgeuponOutcome'].str.split(' ', expand=True)[1])

    df['Age (Weeks)'] = df['Age (Weeks)'].convert_objects(convert_numeric=True)

    df.loc[df['Units'] == 'years','Units'] = 'year'
    df.loc[df['Units'] == 'months','Units'] = 'month'
    df.loc[df['Units'] == 'weeks','Units'] = 'week'

    df.loc[df['Units'] == 'year','Age (Weeks)'] = df.loc[df['Units'] == 'year','Age (Weeks)'] * 52
    df.loc[df['Units'] == 'month','Age (Weeks)'] = df.loc[df['Units'] == 'month','Age (Weeks)'] * 4

    df.loc[df['Age (Weeks)'].isnull(),'Age (Weeks)'] = 0

    df = df.drop(['AgeuponOutcome','Units'],1)

    df['DateTime'] = pd.to_datetime(df['DateTime'])

    df['YearOutcome'] = df['DateTime'].dt.year
    df['MonthOutcome'] = df['DateTime'].dt.month

    df = df.drop('DateTime',1)

    df['HasName'] = ~df['Name'].isnull()

    df = df.drop('Name',axis=1)

    df['IsMix'] = df['Breed'].str.contains('Mix')

    color_list = []

    for color in df['Color'].unique():
        new_colors = color.split('/')
        for new_color in new_colors:
            new_color_list = new_color.split(' ')
            for identifier in new_color_list:
                if str(identifier) not in color_list:
                    color_list.append(str(identifier))

    for color in color_list:
        df[str(color)] = df['Color'].str.contains(color)

    df = df.drop('Color', axis=1)

    breed_list = []

    df['Mixed'] = df['Breed'].str.contains('Mix')
    df['Breed'] = df['Breed'].str.rstrip('Mix').str.rstrip()

    df['PitBull'] = df['Breed'].str.contains('Pit Bull')
    df['Terrier'] = df['Breed'].str.contains('Terrier')
    df['Mini'] = df['Breed'].str.contains('Miniature')

    df_breeds = df['Breed'].reset_index().drop('index',axis=1)
    df_breeds_counts = df_breeds['Breed'].value_counts().to_frame().rename(columns={0L: 'Frequency'})
    df_breeds_counts.insert(0, 'Name', df_breeds_counts)

    df['Corgi'] = df['Breed'].str.contains('Corgi')
    df['Retriever'] = df['Breed'].str.contains('Retriever')
    df['Hound'] = df['Breed'].str.contains('Hound')
    df['Husky'] = df['Breed'].str.contains('Husky')
    df['Beagle'] = df['Breed'].str.contains('Beagle')
    df['Chihuahua'] = df['Breed'].str.contains('Chichuahua')
    df['Bulldog'] = df['Breed'].str.contains('Bulldog')

    df['CatMixed'] = (df['Breed'].str.contains('Domestic Shorthair') |
                     df['Breed'].str.contains('Domestic Longhair') |
                     df['Breed'].str.contains('Domestic Medium Hair'))

    df = df.drop('Breed',axis=1)

    if 'OutcomeSubtype' in df.columns:
        df = df.drop('OutcomeSubtype',axis=1)

In [277]:
combined = cleanFeatures(combined)

In [278]:
combined

,AnimalID,ID,OutcomeType,Male,NeuteredSpayed,SexuponOutcomeKnown,Dog,Age (Weeks),YearOutcome,MonthOutcome,...,Terrier,Mini,Corgi,Retriever,Hound,Husky,Beagle,Chihuahua,Bulldog,CatMixed
0,A671945,NaN,Return_to_owner,True,True,True,True,52,2014,2,...,False,False,False,False,False,False,False,False,False,False
1,A656520,NaN,Euthanasia,False,True,True,False,52,2013,10,...,False,False,False,False,False,False,False,False,False,True
2,A686464,NaN,Adoption,True,True,True,True,104,2015,1,...,False,False,False,False,False,False,False,False,False,False
3,A683430,NaN,Transfer,True,False,True,False,3,2014,7,...,False,False,False,False,False,False,False,False,False,True
4,A667013,NaN,Transfer,True,True,True,True,104,2013,11,...,False,True,False,False,False,False,False,False,False,False
5,A677334,NaN,Transfer,False,False,True,True,4,2014,4,...,True,False,False,False,False,False,False,False,False,False
6,A699218,NaN,Transfer,True,False,True,False,3,2015,3,...,False,False,False,False,False,False,False,False,False,True
7,A701489,NaN,Transfer,False,False,True,False,3,2015,4,...,False,False,False,False,False,False,False,False,False,True
8,A671784,NaN,Adoption,False,True,True,True,20,2014,2,...,True,False,False,False,False,False,False,False,False,False
9,A677747,NaN,Adoption,False,True,True,True,52,2014,5,...,True,False,False,False,False,False,False,False,False,False
10,A668402,NaN,Transfer,False,False,True,False,104,2013,12,...,False,False,False,False,False,False,False,False,False,True
11,A666320,NaN,Adoption,False,True,True,True,104,2013,11,...,False,True,False,False,False,False,False,False,False,False
12,A684601,NaN,Adoption,True,True,True,True,208,2016,2,...,False,False,False,False,False,False,False,False,False,False
13,A704702,NaN,Return_to_owner,True,True,True,True,104,2015,6,...,True,False,False,False,False,False,False,False,False,False
14,A688584,NaN,Return_to_owner,True,True,True,True,52,2015,11,...,False,False,False,False,False,False,False,False,False,False
15,A678825,NaN,Adoption,True,True,True,False,12,2014,7,...,False,False,False,False,False,False,False,False,False,True
16,A678050,NaN,Transfer,True,False,True,False,3,2014,5,...,False,False,False,False,False,False,False,False,False,True
17,A680028,NaN,Transfer,False,False,True,True,2,2014,6,...,False,False,False,False,False,False,False,False,False,False
18,A679010,NaN,Transfer,False,False,True,False,104,2014,5,...,False,False,False,False,False,False,False,False,False,False
19,A684787,NaN,Return_to_owner,True,True,True,True,52,2014,7,...,False,False,False,True,False,False,False,False,False,False
20,A670658,NaN,Transfer,True,False,True,True,8,2014,1,...,False,False,False,False,False,False,False,False,False,False
21,A708812,NaN,Transfer,False,True,True,False,52,2015,9,...,False,False,False,False,False,False,False,False,False,True
22,A705262,NaN,Adoption,False,True,True,True,104,2015,8,...,False,False,False,False,True,False,False,False,False,False
23,A665781,NaN,Adoption,True,True,True,True,40,2013,10,...,False,False,False,False,False,False,False,False,False,False
24,A676333,NaN,Return_to_owner,True,True,True,True,8,2014,4,...,False,False,False,False,False,False,False,False,False,False
25,A712750,NaN,Transfer,False,False,True,False,4,2015,10,...,False,False,False,False,False,False,False,False,False,True
26,A718832,NaN,Adoption,False,True,True,True,24,2016,1,...,True,False,False,False,False,False,False,False,False,False
27,A698777,NaN,Adoption,False,True,True,True,260,2015,3,...,False,False,False,False,False,False,False,False,False,False
28,A715348,NaN,Adoption,False,True,True,False,8,2015,11,...,False,False,False,False,False,False,False,False,False,True
29,A708666,NaN,Return_to_owner,True,True,True,False,364,2015,7,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11426,NaN,11427,NaN,True,True,True,True,260,2013,12,...,False,False,False,False,False,False,False,False,False,False
11427,NaN,11428,NaN,False,False,True,True,8,2013,12,...,True,False,False,False,False,False,False,False,False,False
11428,NaN,11429,NaN,True,True,True,True,156,2013,11,...,False,False,False,False,False,True,False,False,False,False
11429,NaN,11430,NaN,False,True,True,True,104,2014,2,...,False,False,False,False,False,False,False,False,False,False
11430,NaN,11431,NaN,False,True,True,False,8,2014,12,...,False,False,False,False,False,False,False,False,False,True
11431,NaN,11432,NaN,True,False,True,False,104,2015,6,...,False,False,False,False,False,False,False,False,False,True
11432,NaN,11433,NaN,False,True,True,True,260,2014,3,...,False,False,False,False,False,False,False,False,False,False
11433,NaN,11434,NaN,False,False,True,False,8,2015,8,...,False,False,False,False,False,False,False,False,False,True
11434,NaN,11435,NaN,False,True,True,True,312,2015,9,...,False,False,True,False,False,False,False,False,False,False
11435,NaN,11436,NaN,True,False,True,False,3,2015,8,...,False,False,False,False,False,False,False,False,False,True
11436,NaN,11437,NaN,True,True,True,False,20,2014,3,...,False,False,False,False,False,False,False,False,False,True
11437,NaN,11438,NaN,False,False,True,True,24,2014,1,...,False,False,False,False,False,False,False,False,False,False
11438,NaN,11439,NaN,True,True,True,True,4,2015,5,...,False,False,False,True,False,False,False,False,False,False
11439,NaN,11440,NaN,False,True,True,True,104,2014,5,...,False,False,False,False,False,False,False,False,False,False
11440,NaN,11441,NaN,False,False,True,False,1,2015,10,...,False,False,False,False,False,False,False,False,False,True
11441,NaN,11442,NaN,True,True,True,True,208,2015,1,...,False,False,False,False,False,False,False,False,False,False
11442,NaN,11443,NaN,True,True,True,True,104,2015,11,...,False,False,False,False,False,False,False,False,False,False
11443,NaN,11444,NaN,False,True,True,False,24,2014,10,...,False,False,False,False,False,False,False,False,False,True
11444,NaN,11445,NaN,False,False,True,False,104,2014,6,...,False,False,False,False,False,False,False,False,False,True
11445,NaN,11446,NaN,True,False,True,False,2,2015,4,...,False,False,False,False,False,False,False,False,False,True
11446,NaN,11447,NaN,True,True,True,False,8,2015,7,...,False,False,False,False,False,False,False,False,False,True
11447,NaN,11448,NaN,False,True,True,True,52,2014,10,...,False,False,False,False,False,False,False,False,False,False
11448,NaN,11449,NaN,False,True,True,True,8,2014,8,...,False,False,False,True,False,False,False,False,False,False
11449,NaN,11450,NaN,False,True,True,True,24,2015,7,...,False,False,False,False,False,False,False,False,False,False
11450,NaN,11451,NaN,True,True,True,True,40,2015,11,...,False,False,False,False,False,False,False,False,False,False
11451,NaN,11452,NaN,True,True,True,False,8,2014,7,...,False,False,False,False,False,False,False,False,False,True
11452,NaN,11453,NaN,False,False,True,False,2,2014,10,...,False,False,False,False,False,False,False,False,False,True
11453,NaN,11454,NaN,False,False,True,False,52,2014,9,...,False,False,False,False,False,False,False,False,False,True
11454,NaN,11455,NaN,True,True,True,True,312,2015,9,...,False,False,False,False,False,False,False,False,False,False
11455,NaN,11456,NaN,True,False,True,True,208,2014,7,...,False,False,False,True,False,False,False,False,False,False

In [279]:
train_cleaned = combined[combined['ID'].isnull()].drop('ID',axis=1)

In [282]:
test_cleaned = combined[combined['AnimalID'].isnull()].drop('AnimalID',axis=1)

## RandomForest Implementation

In [283]:
train_y = train_cleaned['OutcomeType']
train_X = train_cleaned.drop(['OutcomeType','AnimalID'],axis=1)

In [289]:
test_X = test_cleaned.drop(['ID','OutcomeType'],axis=1)

In [285]:
rf = RandomForestClassifier(n_estimators=100)

In [291]:
rf.fit(train_X, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [306]:
predictions = rf.predict_proba(test_X)

In [303]:
headers = ['AnimalID','Adoption','Died','Euthanasia','Return_to_owner','Transfer']

In [312]:
output_df = pd.DataFrame(columns=headers)

In [317]:
test_cleaned['ID'] = 'A' + test_cleaned['ID'].astype(str)

In [318]:
test_cleaned

,ID,OutcomeType,Male,NeuteredSpayed,SexuponOutcomeKnown,Dog,Age (Weeks),YearOutcome,MonthOutcome,HasName,...,Terrier,Mini,Corgi,Retriever,Hound,Husky,Beagle,Chihuahua,Bulldog,CatMixed
0,A1.0,NaN,False,False,True,True,40,2015,10,True,...,False,False,False,True,False,False,False,False,False,False
1,A2.0,NaN,False,True,True,True,104,2014,7,True,...,False,False,False,False,False,True,False,False,False,False
2,A3.0,NaN,True,True,True,False,52,2016,1,True,...,False,False,False,False,False,False,False,False,False,True
3,A4.0,NaN,True,False,True,True,16,2013,12,True,...,False,False,False,False,False,False,False,False,False,False
4,A5.0,NaN,True,True,True,True,104,2015,9,True,...,False,True,False,False,False,False,False,False,False,False
5,A6.0,NaN,True,True,True,True,156,2015,6,True,...,False,False,False,False,False,False,True,False,False,False
6,A7.0,NaN,True,True,True,False,676,2014,3,True,...,False,False,False,False,False,False,False,False,False,True
7,A8.0,NaN,False,True,True,False,24,2014,6,True,...,False,False,False,False,False,False,False,False,False,True
8,A9.0,NaN,False,True,True,True,12,2014,11,True,...,True,False,False,False,False,False,False,False,False,False
9,A10.0,NaN,False,True,True,True,52,2014,4,True,...,False,False,False,False,False,False,False,False,False,False
10,A11.0,NaN,False,True,True,True,20,2014,1,True,...,False,False,False,True,False,False,False,False,False,False
11,A12.0,NaN,False,False,True,True,104,2014,9,True,...,False,False,False,False,False,False,False,False,False,False
12,A13.0,NaN,False,True,True,True,24,2015,1,True,...,False,False,False,False,False,False,False,False,False,False
13,A14.0,NaN,True,True,True,True,104,2015,9,False,...,False,True,False,False,False,False,False,False,False,False
14,A15.0,NaN,True,True,True,True,52,2014,7,True,...,False,False,False,True,False,False,False,False,False,False
15,A16.0,NaN,False,True,True,True,16,2014,3,True,...,False,False,False,True,False,False,False,False,False,False
16,A17.0,NaN,True,True,True,True,260,2015,5,True,...,False,False,False,False,False,False,False,False,False,False
17,A18.0,NaN,True,True,True,True,156,2016,1,True,...,False,False,False,False,False,False,False,False,True,False
18,A19.0,NaN,False,True,True,False,156,2014,6,True,...,False,False,False,False,False,False,False,False,False,True
19,A20.0,NaN,False,False,True,False,208,2014,2,False,...,False,False,False,False,False,False,False,False,False,True
20,A21.0,NaN,False,True,True,False,104,2014,11,True,...,False,False,False,False,False,False,False,False,False,True
21,A22.0,NaN,False,False,True,False,3,2015,5,False,...,False,False,False,False,False,False,False,False,False,True
22,A23.0,NaN,True,True,True,True,52,2014,6,True,...,True,False,False,False,False,False,False,False,False,False
23,A24.0,NaN,False,False,True,False,1,2014,7,False,...,False,False,False,False,False,False,False,False,False,True
24,A25.0,NaN,False,True,True,True,52,2013,10,True,...,False,False,False,False,False,False,False,False,False,False
25,A26.0,NaN,True,True,True,False,52,2014,12,False,...,False,False,False,False,False,False,False,False,False,True
26,A27.0,NaN,False,True,True,False,8,2015,7,True,...,False,False,False,False,False,False,False,False,False,True
27,A28.0,NaN,True,False,True,True,8,2015,3,False,...,True,False,False,False,False,False,False,False,False,False
28,A29.0,NaN,True,True,True,True,156,2014,10,True,...,False,False,False,True,False,False,False,False,False,False
29,A30.0,NaN,True,True,True,True,104,2014,5,True,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11426,A11427.0,NaN,True,True,True,True,260,2013,12,True,...,False,False,False,False,False,False,False,False,False,False
11427,A11428.0,NaN,False,False,True,True,8,2013,12,True,...,True,False,False,False,False,False,False,False,False,False
11428,A11429.0,NaN,True,True,True,True,156,2013,11,True,...,False,False,False,False,False,True,False,False,False,False
11429,A11430.0,NaN,False,True,True,True,104,2014,2,True,...,False,False,False,False,False,False,False,False,False,False
11430,A11431.0,NaN,False,True,True,False,8,2014,12,False,...,False,False,False,False,False,False,False,False,False,True
11431,A11432.0,NaN,True,False,True,False,104,2015,6,False,...,False,False,False,False,False,False,False,False,False,True
11432,A11433.0,NaN,False,True,True,True,260,2014,3,True,...,False,False,False,False,False,False,False,False,False,False
11433,A11434.0,NaN,False,False,True,False,8,2015,8,True,...,False,False,False,False,False,False,False,False,False,True
11434,A11435.0,NaN,False,True,True,True,312,2015,9,True,...,False,False,True,False,False,False,False,False,False,False
11435,A11436.0,NaN,True,False,True,False,3,2015,8,False,...,False,False,False,False,False,False,False,False,False,True
11436,A11437.0,NaN,True,True,True,False,20,2014,3,False,...,False,False,False,False,False,False,False,False,False,True
11437,A11438.0,NaN,False,False,True,True,24,2014,1,True,...,False,False,False,False,False,False,False,False,False,False
11438,A11439.0,NaN,True,True,True,True,4,2015,5,False,...,False,False,False,True,False,False,False,False,False,False
11439,A11440.0,NaN,False,True,True,True,104,2014,5,True,...,False,False,False,False,False,False,False,False,False,False
11440,A11441.0,NaN,False,False,True,False,1,2015,10,False,...,False,False,False,False,False,False,False,False,False,True
11441,A11442.0,NaN,True,True,True,True,208,2015,1,True,...,False,False,False,False,False,False,False,False,False,False
11442,A11443.0,NaN,True,True,True,True,104,2015,11,True,...,False,False,False,False,False,False,False,False,False,False
11443,A11444.0,NaN,False,True,True,False,24,2014,10,True,...,False,False,False,False,False,False,False,False,False,True
11444,A11445.0,NaN,False,False,True,False,104,2014,6,False,...,False,False,False,False,False,False,False,False,False,True
11445,A11446.0,NaN,True,False,True,False,2,2015,4,False,...,False,False,False,False,False,False,False,False,False,True
11446,A11447.0,NaN,True,True,True,False,8,2015,7,False,...,False,False,False,False,False,False,False,False,False,True
11447,A11448.0,NaN,False,True,True,True,52,2014,10,True,...,False,False,False,False,False,False,False,False,False,False
11448,A11449.0,NaN,False,True,True,True,8,2014,8,False,...,False,False,False,True,False,False,False,False,False,False
11449,A11450.0,NaN,False,True,True,True,24,2015,7,True,...,False,False,False,False,False,False,False,False,False,False
11450,A11451.0,NaN,True,True,True,True,40,2015,11,True,...,False,False,False,False,False,False,False,False,False,False
11451,A11452.0,NaN,True,True,True,False,8,2014,7,False,...,False,False,False,False,False,False,False,False,False,True
11452,A11453.0,NaN,False,False,True,False,2,2014,10,False,...,False,False,False,False,False,False,False,False,False,True
11453,A11454.0,NaN,False,False,True,False,52,2014,9,False,...,False,False,False,False,False,False,False,False,False,True
11454,A11455.0,NaN,True,True,True,True,312,2015,9,True,...,False,False,False,False,False,False,False,False,False,False
11455,A11456.0,NaN,True,False,True,True,208,2014,7,True,...,False,False,False,True,False,False,False,False,False,False